// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crehaszdmqmvqlhxrqzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZWhhc3pkbXFtdnFsaHhycXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzUyNDUsImV4cCI6MjA2MzQxMTI0NX0.CT80eH3GJCX1UE0F7oUc-2_ZgurpgsrPil4Owl8Crk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);